import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/assets/css/globals.css";
import * as React from "react";

const inter = Inter({ subsets: ["latin"] });
import { NextUIProvider } from "@nextui-org/react";
import CustomNaviation from '@/components/molecules/navbar'

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={"dark text-foreground bg-background"}>
        <NextUIProvider>
          <CustomNaviation />
          {children}
        </NextUIProvider>
      </body>
    </html>
  );
}
